title: Dhawin Kritsernvong
logo: /assets/img/profile.jpg
#description: text below image
email: k.dhawin@gmail.com
show_downloads: true
  github:  
      zip_url: https://dhawin.github.io/Portfolio/
      tar_url: https://dhawin.github.io/Portfolio/
theme: jekyll-theme-minimal
